VERSION="2.2.1"

ACCOUNTS=["GAVKJUTEUK7JUUQFYNCIJOJVS4NSU63YCAGMUVTSMGUN5CA4XEEFIETQ"]

[DOCUMENTATION]
ORG_NAME="Cash App"
ORG_URL="https://www.cashapp-stellar.com/"
ORG_DESCRIPTION="Cash App is a mobile payment service available in the United States and the United Kingdom that allows users to transfer money to one another using a mobile phone app."
ORG_LOGO="https://www.cashapp-stellar.com/cashapp.jpg"


[[CURRENCIES]]
code="CAXLM"
status="live"
display_decimals=4
issuer="GAVKJUTEUK7JUUQFYNCIJOJVS4NSU63YCAGMUVTSMGUN5CA4XEEFIETQ"
anchor_asset_type="crypto"
name="Cash App XLM"
desc="Buy now Cash App XLM and be one of the first to get it into the App!"
image="https://www.cashapp-stellar.com/cashapp.jpg"
