VERSION="2.2.1"

ACCOUNTS=["GBAXHLCHBI6ALVWWS7BK23Q2ZNM4GH6LO7AVMT2IMW4ZQ6DMTWBYHZYR"]

[DOCUMENTATION]
ORG_NAME="Travala"
ORG_URL="https://www.travala-stellar.com/"
ORG_DESCRIPTION="Book over 3 Million travel products around the world with popular cryptocurrencies. Find and book Hotels, Flights, Tours and Activities online today."
ORG_LOGO="https://www.travala-stellar.com/logo.png"


[[CURRENCIES]]
code="AVA"
status="live"
display_decimals=3
issuer="GBAXHLCHBI6ALVWWS7BK23Q2ZNM4GH6LO7AVMT2IMW4ZQ6DMTWBYHZYR"
anchor_asset_type="crypto"
name="Travala"
desc="Book over 3 Million travel products around the world with popular cryptocurrencies. Find and book Hotels, Flights, Tours and Activities online today."
image="https://www.travala-stellar.com/logo.png"
