VERSION="2.2.1"

ACCOUNTS=["GAJBTODLHJTFUQTYGLVGGTU3SCZJZMLZYBRWAJNLKTJXFLJLKSCLPVHE"]

[DOCUMENTATION]
ORG_NAME="GoFundMe"
ORG_URL="https://www.gofundstellar.com/"
ORG_DESCRIPTION="Your home for help. Discover fundraisers inspired by what you care about."
ORG_LOGO="https://www.gofundstellar.com/gfm.jpg"


[[CURRENCIES]]
code="GFM"
status="live"
display_decimals=4
issuer="GAJBTODLHJTFUQTYGLVGGTU3SCZJZMLZYBRWAJNLKTJXFLJLKSCLPVHE"
anchor_asset_type="crypto"
name="GoFundMe"
desc="Your home for help. Discover fundraisers inspired by what you care about."
image="https://www.gofundstellar.com/gfm.jpg"
